name: Copy files from repository1
on:
  repository_dispatch:
    types: [target-updated]
jobs:
  copy-target:
    name: Copy files from src folder
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: clone repository1
        uses: actions/checkout@v2
        with:
          repository: tsubasa-admin/common_repo
          path: common_repo
          token: ${{ secrets.TEST_WR_REPO_ACCESS_TOKEN }}
      - name: Create src folder
        run: mkdir -p src
      - name: Copy files to src folder
        run: cp -R common_repo/src/. src/.
      - name: List copied files
        run: ls -R src
      - name: create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.TEST_WR_REPO_ACCESS_TOKEN }}
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit-message: 'Copy files to src folder'
          branch: copy_target
          branch-suffix: timestamp
          delete-branch: true
          title: 'Update files in src folder'